// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxjVndhShr7PxNB5HArjHKP5dzRbPteYY',
    appId: '1:435773074886:web:8599c4bb2a4361cd1616c7',
    messagingSenderId: '435773074886',
    projectId: 'erp-shop-management',
    authDomain: 'erp-shop-management.firebaseapp.com',
    storageBucket: 'erp-shop-management.firebasestorage.app',
    measurementId: 'G-DZ0C20PKQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4gjBrFu1EgyMofgVavfXU41xpbPLTIVI',
    appId: '1:435773074886:android:e662b746e903c9401616c7',
    messagingSenderId: '435773074886',
    projectId: 'erp-shop-management',
    storageBucket: 'erp-shop-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkCQ41pK1b6m2Fj8tVNNyWJ3YRHiEuWTs',
    appId: '1:435773074886:ios:aadebbbf37f99fb51616c7',
    messagingSenderId: '435773074886',
    projectId: 'erp-shop-management',
    storageBucket: 'erp-shop-management.firebasestorage.app',
    iosBundleId: 'com.example.erp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkCQ41pK1b6m2Fj8tVNNyWJ3YRHiEuWTs',
    appId: '1:435773074886:ios:aadebbbf37f99fb51616c7',
    messagingSenderId: '435773074886',
    projectId: 'erp-shop-management',
    storageBucket: 'erp-shop-management.firebasestorage.app',
    iosBundleId: 'com.example.erp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxjVndhShr7PxNB5HArjHKP5dzRbPteYY',
    appId: '1:435773074886:web:dbdad64c0fa9886c1616c7',
    messagingSenderId: '435773074886',
    projectId: 'erp-shop-management',
    authDomain: 'erp-shop-management.firebaseapp.com',
    storageBucket: 'erp-shop-management.firebasestorage.app',
    measurementId: 'G-M13C9NW0EE',
  );
}
